version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cabbookingapplication
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
